apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tf-internal-only
  namespace: tensor-fabric
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: tensor-fabric
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: tensor-fabric
    - ports:
        - port: 443
          protocol: TCP
        - port: 53
          protocol: UDP
